name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    #timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create a shared network
      - name: create a docker network
        run: |
          docker network create test-network
      
      # Setup directories with correct permissions
      - name: Prepare results directory
        run: |
          mkdir results
          chmod 775 results  # Read/write for group
          touch /results/output.json
          ls -atlr


      # Set up Docker container
      - name: Build and run app
        run: |
          docker build -t ui-testing-app .
          docker run -d -p 5000:5000 --name ui-app --network test-network ui-testing-app
          sleep 30  # Wait for app to start
          
      # Return the logs for ui-app
      - name: Check container logs
        run: docker logs ui-app

      # Install wait-on
      - name: Install wait-on
        run: |
          npm install --save-dev wait-on

      # Wait for app to be ready
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5000 --timeout 30000

      # Verify container status
      - name: Check container health
        run: docker ps -a

      # Install Cypress and dependencies
      - name: Install dependencies
        run: |
          npm init -y  # Only needed if no package.json exists
          npm install cypress wait-on --save-dev

      # Run Cypress tests against the Docker container
      - name: Run Cypress tests
        run: npx cypress run --browser chrome --reporter json
        env:
          CYPRESS_baseUrl: http://localhost:5000

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependecies
      - name: Install dependencies
        run: npm ci
     
      # install Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Install @playwright/test
      - name: Install @playwright/test
        run: npm install --save-dev @playwright/test

      # Run Playwright test
      - name: Run Playwright tests
        run: |
          echo "Running playwright test"
          npx playwright test

      # Run k6 tests with proper volume mounting
      - name: Execute performance tests
        run: |
          docker run \
            --rm \
            --network test-network \
            -v "$(pwd)/performance-tests:/scripts" \
            -v "$(pwd)/performance-tests/results:/results" \
            grafana/k6 run \
            --out json=/results/output.json \
            /scripts/login-test.js

      # Upload results
      - name: Store test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: performance-tests/results/*

      # Cleanup (optional)
      - name: Stop container
        if: always()  # Runs even if tests fail
        run: docker stop ui-app