name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker container
      - name: Build and run app
        run: |
          docker build -t ui-testing-app .
          docker run -d -p 5000:5000 --name ui-app --health-cmd="curl -f http://localhost:5000 || exit 1" --health-interval=2s --health-retries=30 ui-testing-app
          sleep 15  # Wait for app to start

          # Wait for container to be healthy
          docker inspect --format='{{json .State.Health.Status}}' ui-app | grep -q '"healthy"'
          sleep 5  # Additional buffer time

      # Verify container status
      - name: Check container health
        run: docker ps -a
        
      # Install Cypress and dependencies
      - name: Install dependencies
        run: |
          npm init -y  # Only needed if no package.json exists
          npm install cypress --save-dev

      # Run Cypress tests against the Docker container
      - name: Run Cypress tests
        run: npx cypress run --browser chrome
        env:
          CYPRESS_baseUrl: http://localhost:5000
    
      # # Optional: Store videos
      # - uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos

      # Cleanup (optional)
      - name: Stop container
        if: always()  # Runs even if tests fail
        run: docker stop ui-app