name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker container
      - name: Build and run app
        run: |
          docker build -t ui-testing-app .
          docker run -d -p 5000:5000 --name ui-app ui-testing-app
          sleep 30  # Wait for app to start

      # Install wait-on
      - name: Install wait-on
        run: |
          npm install --save-dev wait-on

      # Wait for app to be ready
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5000

      # Verify container status
      - name: Check container health
        run: docker ps -a

      # Install Cypress and dependencies
      - name: Install dependencies
        run: |
          npm init -y  # Only needed if no package.json exists
          npm install cypress wait-on --save-dev

      # Run Cypress tests against the Docker container
      - name: Run Cypress tests
        run: npx cypress run --browser chrome --reporter json
        env:
          CYPRESS_baseUrl: http://localhost:5000

      # Cleanup (optional)
      - name: Stop container
        if: always()  # Runs even if tests fail
        run: docker stop ui-app